"""
Python Program:
 Using collections.Counter() to print the char frequency in string
"""
from collections import Counter

input_string = "GFS WMY OG LGDVS MF SFNKYHOSU ESLLMRS, PC WS BFGW POL DMFRQMRS, PL OG CPFU M UPCCSKSFO HDMPFOSXO GC OIS LMES DMFRQMRS DGFR SFGQRI OG CPDD GFS LISSO GK LG, MFU OISF WS NGQFO OIS GNNQKKSFNSL GC SMNI DSOOSK. WS NMDD OIS EGLO CKSJQSFODY GNNQKKPFR DSOOSK OIS 'CPKLO', OIS FSXO EGLO GNNQKKPFR DSOOSK OIS 'LSNGFU' OIS CGDDGWPFR EGLO GNNQKKPFR DSOOSK OIS 'OIPKU', MFU LG GF, QFOPD WS MNNGQFO CGK MDD OIS UPCCSKSFO DSOOSKL PF OIS HDMPFOSXO LMEHDS. OISF WS DGGB MO OIS NPHISK OSXO WS WMFO OG LGDVS MFU WS MDLG NDMLLPCY POL LYEAGDL. WS CPFU OIS EGLO GNNQKKPFR LYEAGD MFU NIMFRS PO OG OIS CGKE GC OIS 'CPKLO' DSOOSK GC OIS HDMPFOSXO LMEHDS, OIS FSXO EGLO NGEEGF LYEAGD PL NIMFRSU OG OIS CGKE GC OIS 'LSNGFU' DSOOSK, MFU OIS CGDDGWPFR EGLO NGEEGF LYEAGD PL NIMFRSU OG OIS CGKE GC OIS 'OIPKU' DSOOSK, MFU LG GF, QFOPD WS MNNGQFO CGK MDD LYEAGDL GC OIS NKYHOGRKME WS WMFO OG LGDVS."
frequency_per_char = Counter(input_string)

# Show Output
print ("Per char frequency in '{}' is :\n {}".format(input_string, str(frequency_per_char)))
print ("Typeof frequency_per_char is: ",type(frequency_per_char))


string_a = "GFS WMY OG LGDVS MF SFNKYHOSU ESLLMRS, PC WS BFGW POL DMFRQMRS, PL OG CPFU M UPCCSKSFO HDMPFOSXO GC OIS LMES DMFRQMRS DGFR SFGQRI OG CPDD GFS LISSO GK LG, MFU OISF WS NGQFO OIS GNNQKKSFNSL GC SMNI DSOOSK. WS NMDD OIS EGLO CKSJQSFODY GNNQKKPFR DSOOSK OIS 'CPKLO', OIS FSXO EGLO GNNQKKPFR DSOOSK OIS 'LSNGFU' OIS CGDDGWPFR EGLO GNNQKKPFR DSOOSK OIS 'OIPKU', MFU LG GF, QFOPD WS MNNGQFO CGK MDD OIS UPCCSKSFO DSOOSKL PF OIS HDMPFOSXO LMEHDS. OISF WS DGGB MO OIS NPHISK OSXO WS WMFO OG LGDVS MFU WS MDLG NDMLLPCY POL LYEAGDL. WS CPFU OIS EGLO GNNQKKPFR LYEAGD MFU NIMFRS PO OG OIS CGKE GC OIS 'CPKLO' DSOOSK GC OIS HDMPFOSXO LMEHDS, OIS FSXO EGLO NGEEGF LYEAGD PL NIMFRSU OG OIS CGKE GC OIS 'LSNGFU' DSOOSK, MFU OIS CGDDGWPFR EGLO NGEEGF LYEAGD PL NIMFRSU OG OIS CGKE GC OIS 'OIPKU' DSOOSK, MFU LG GF, QFOPD WS MNNGQFO CGK MDD LYEAGDL GC OIS NKYHOGRKME WS WMFO OG LGDVS."
string_b = string_a.replace("G","o")
print(string_a)
print(string_b)

string_c = "oFS WMY Oo LoDVS MF SFNKYHOSU ESLLMRS, PC WS BFoW POL DMFRQMRS, PL Oo CPFU M UPCCSKSFO HDMPFOSXO oC OIS LMES DMFRQMRS DoFR SFoQRI Oo CPDD oFS LISSO oK Lo, MFU OISF WS NoQFO OIS oNNQKKSFNSL oC SMNI DSOOSK. WS NMDD OIS EoLO CKSJQSFODY oNNQKKPFR DSOOSK OIS 'CPKLO', OIS FSXO EoLO oNNQKKPFR DSOOSK OIS 'LSNoFU' OIS CoDDoWPFR EoLO oNNQKKPFR DSOOSK OIS 'OIPKU', MFU Lo oF, QFOPD WS MNNoQFO CoK MDD OIS UPCCSKSFO DSOOSKL PF OIS HDMPFOSXO LMEHDS. OISF WS DooB MO OIS NPHISK OSXO WS WMFO Oo LoDVS MFU WS MDLo NDMLLPCY POL LYEAoDL. WS CPFU OIS EoLO oNNQKKPFR LYEAoD MFU NIMFRS PO Oo OIS CoKE oC OIS 'CPKLO' DSOOSK oC OIS HDMPFOSXO LMEHDS, OIS FSXO EoLO NoEEoF LYEAoD PL NIMFRSU Oo OIS CoKE oC OIS 'LSNoFU' DSOOSK, MFU OIS CoDDoWPFR EoLO NoEEoF LYEAoD PL NIMFRSU Oo OIS CoKE oC OIS 'OIPKU' DSOOSK, MFU Lo oF, QFOPD WS MNNoQFO CoK MDD LYEAoDL oC OIS NKYHOoRKME WS WMFO Oo LoDVS."
string_d = string_c.replace("F","n")
print(string_c)
print(string_d)

string_e = "onS WMY Oo LoDVS Mn SnNKYHOSU ESLLMRS, PC WS BnoW POL DMnRQMRS, PL Oo CPnU M UPCCSKSnO HDMPnOSXO oC OIS LMES DMnRQMRS DonR SnoQRI Oo CPDD onS LISSO oK Lo, MnU OISn WS NoQnO OIS oNNQKKSnNSL oC SMNI DSOOSK. WS NMDD OIS EoLO CKSJQSnODY oNNQKKPnR DSOOSK OIS 'CPKLO', OIS nSXO EoLO oNNQKKPnR DSOOSK OIS 'LSNonU' OIS CoDDoWPnR EoLO oNNQKKPnR DSOOSK OIS 'OIPKU', MnU Lo on, QnOPD WS MNNoQnO CoK MDD OIS UPCCSKSnO DSOOSKL Pn OIS HDMPnOSXO LMEHDS. OISn WS DooB MO OIS NPHISK OSXO WS WMnO Oo LoDVS MnU WS MDLo NDMLLPCY POL LYEAoDL. WS CPnU OIS EoLO oNNQKKPnR LYEAoD MnU NIMnRS PO Oo OIS CoKE oC OIS 'CPKLO' DSOOSK oC OIS HDMPnOSXO LMEHDS, OIS nSXO EoLO NoEEon LYEAoD PL NIMnRSU Oo OIS CoKE oC OIS 'LSNonU' DSOOSK, MnU OIS CoDDoWPnR EoLO NoEEon LYEAoD PL NIMnRSU Oo OIS CoKE oC OIS 'OIPKU' DSOOSK, MnU Lo on, QnOPD WS MNNoQnO CoK MDD LYEAoDL oC OIS NKYHOoRKME WS WMnO Oo LoDVS."
string_f = string_e.replace("S","e")
print(string_f)

string_g = "one WMY Oo LoDVe Mn enNKYHOeU EeLLMRe, PC We BnoW POL DMnRQMRe, PL Oo CPnU M UPCCeKenO HDMPnOeXO oC OIe LMEe DMnRQMRe DonR enoQRI Oo CPDD one LIeeO oK Lo, MnU OIen We NoQnO OIe oNNQKKenNeL oC eMNI DeOOeK. We NMDD OIe EoLO CKeJQenODY oNNQKKPnR DeOOeK OIe 'CPKLO', OIe neXO EoLO oNNQKKPnR DeOOeK OIe 'LeNonU' OIe CoDDoWPnR EoLO oNNQKKPnR DeOOeK OIe 'OIPKU', MnU Lo on, QnOPD We MNNoQnO CoK MDD OIe UPCCeKenO DeOOeKL Pn OIe HDMPnOeXO LMEHDe. OIen We DooB MO OIe NPHIeK OeXO We WMnO Oo LoDVe MnU We MDLo NDMLLPCY POL LYEAoDL. We CPnU OIe EoLO oNNQKKPnR LYEAoD MnU NIMnRe PO Oo OIe CoKE oC OIe 'CPKLO' DeOOeK oC OIe HDMPnOeXO LMEHDe, OIe neXO EoLO NoEEon LYEAoD PL NIMnReU Oo OIe CoKE oC OIe 'LeNonU' DeOOeK, MnU OIe CoDDoWPnR EoLO NoEEon LYEAoD PL NIMnReU Oo OIe CoKE oC OIe 'OIPKU' DeOOeK, MnU Lo on, QnOPD We MNNoQnO CoK MDD LYEAoDL oC OIe NKYHOoRKME We WMnO Oo LoDVe."
string_h = string_g.replace("M","a")
print(string_h)



